/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/common/Counter.vue')['default']
    ElB: typeof import('element-plus/es')['ElB']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    FormValidate: typeof import('./src/components/common/FormValidate.vue')['default']
    GoodsList: typeof import('./src/components/content/GoodsList.vue')['default']
    MySwiper: typeof import('./src/components/common/MySwiper.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    PCFooter: typeof import('./src/components/content/PCFooter.vue')['default']
    PCHeader: typeof import('./src/components/content/PCHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopInfo: typeof import('./src/components/content/ShopInfo.vue')['default']
    ShopList: typeof import('./src/components/content/ShopList.vue')['default']
  }
}
